# Generated by Django 6.0.1 on 2026-01-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription_pdf',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
